# Data Processing

After extracting data from Google BigQuery. This python script will be used to process data specifc to ENS

In [117]:
# import to invoke required module
import pandas as pd
import numpy as np
from tabulate import tabulate
from prettytable import PrettyTable
# Dataframe display options
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 5000)

# Post ENS Data Preparation

In [96]:
dfTrace = pd.read_csv('/Users/rparama/Downloads/Dataset/1_ETH_DataPrepration.csv')
dfTrace.head()

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (4,16) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

                                    transaction_hash  transaction_index                              from_address_x                                to_address_x              value_x                                              input                                             output       gas  gas_used  subtraces          block_timestamp_x  block_number_x                                       block_hash_x                               token_address                              from_address_y                                to_address_y    value_y  log_index          block_timestamp_y  block_number_y                                       block_hash_y
0  0x12d11793515571efff5f876397e714aa4d1cf3b82749...                7.0  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x51a5c4d6b39b4f789464a9a8e434447764953f92  3600000000000000000                                                 0x                                                 0x    2300.0       0.0          0  2019-11-16 03:48:38+00:00         9197934  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...  0xac55641cbb734bdf6510d1bbd62e240c2409040f  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x94f9e355fe66eeb5bf8b09fbdf493e1f64680f2a  400000000          5  2019-11-16 03:48:38+00:00         9197934  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...
1  0x12d11793515571efff5f876397e714aa4d1cf3b82749...                7.0  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x51a5c4d6b39b4f789464a9a8e434447764953f92  3600000000000000000                                                 0x                                                 0x    2300.0       0.0          0  2019-11-16 03:48:38+00:00         9197934  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...  0xac55641cbb734bdf6510d1bbd62e240c2409040f  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x94f9e355fe66eeb5bf8b09fbdf493e1f64680f2a     902255          8  2019-11-16 03:48:38+00:00         9197934  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...
2  0x12d11793515571efff5f876397e714aa4d1cf3b82749...                7.0  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0xac55641cbb734bdf6510d1bbd62e240c2409040f                    0  0xa9059cbb00000000000000000000000094f9e355fe66...  0x00000000000000000000000000000000000000000000...   78557.0   17277.0          0  2019-11-16 03:48:38+00:00         9197934  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...  0xac55641cbb734bdf6510d1bbd62e240c2409040f  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x94f9e355fe66eeb5bf8b09fbdf493e1f64680f2a  400000000          5  2019-11-16 03:48:38+00:00         9197934  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...
3  0x12d11793515571efff5f876397e714aa4d1cf3b82749...                7.0  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0xac55641cbb734bdf6510d1bbd62e240c2409040f                    0  0xa9059cbb00000000000000000000000094f9e355fe66...  0x00000000000000000000000000000000000000000000...   78557.0   17277.0          0  2019-11-16 03:48:38+00:00         9197934  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...  0xac55641cbb734bdf6510d1bbd62e240c2409040f  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x94f9e355fe66eeb5bf8b09fbdf493e1f64680f2a     902255          8  2019-11-16 03:48:38+00:00         9197934  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...
4  0x12d11793515571efff5f876397e714aa4d1cf3b82749...                7.0  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0xac55641cbb734bdf6510d1bbd62e240c2409040f                    0  0xa9059cbb00000000000000000000000094f9e355fe66...  0x00000000000000000000000000000000000000000000...  115590.0   17277.0          0  2019-11-16 03:48:38+00:00         9197934  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...  0xac55641cbb734bdf6510d1bbd62e240c2409040f  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x94f9e355fe66eeb5bf8b09fbdf493e1f64680f2a  400000000          5  2019-11-16 03:48:38+00:00         9197934  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...

In [22]:
# File metadata/Schema analysis


headers=PrettyTable(["Column Name","Record Count","Unique Count","Null Count","Total Count"])
for col in dfTrace.columns:
    headers.add_row([col,dfTrace[col].count(),dfTrace[col].nunique(),
                    dfTrace[col].isnull().sum(),dfTrace[col].count()+dfTrace[col].isnull().sum()])
print(headers)

+-------------------+--------------+--------------+------------+-------------+
|    Column Name    | Record Count | Unique Count | Null Count | Total Count |
+-------------------+--------------+--------------+------------+-------------+
|  transaction_hash |   1598326    |    156381    |     0      |   1598326   |
| transaction_index |   1598326    |     206      |     0      |   1598326   |
|   from_address_x  |   1598326    |     2880     |     0      |   1598326   |
|    to_address_x   |   1598326    |     935      |     0      |   1598326   |
|      value_x      |   1598326    |    20855     |     0      |   1598326   |
|       input       |   1598326    |    219587    |     0      |   1598326   |
|       output      |   1598326    |     4909     |     0      |   1598326   |
|        gas        |   1598326    |    84592     |     0      |   1598326   |
|      gas_used     |   1598326    |    11780     |     0      |   1598326   |
|     subtraces     |   1598326    |      34      |     0      |   1598326   |
| block_timestamp_x |   1598326    |    69457     |     0      |   1598326   |
|   block_number_x  |   1598326    |    69457     |     0      |   1598326   |
|    block_hash_x   |   1598326    |    69457     |     0      |   1598326   |
|   token_address   |   1598326    |     148      |     0      |   1598326   |
|   from_address_y  |   1598326    |     2566     |     0      |   1598326   |
|    to_address_y   |   1598326    |    28948     |     0      |   1598326   |
|      value_y      |   1598326    |    32176     |     0      |   1598326   |
|     log_index     |   1598326    |     353      |     0      |   1598326   |
| block_timestamp_y |   1598326    |    69457     |     0      |   1598326   |
|   block_number_y  |   1598326    |    69457     |     0      |   1598326   |
|    block_hash_y   |   1598326    |    69457     |     0      |   1598326   |
+-------------------+--------------+--------------+------------+-------------+

In [99]:
dfTrace = dfTrace[(dfTrace['block_timestamp_x'] == dfTrace['block_timestamp_y']) &
                  (dfTrace['block_number_x'] == dfTrace['block_number_y']) &
                  (dfTrace['block_hash_x'] == dfTrace['block_hash_y']) 
                 ]

In [103]:
headers=PrettyTable(["S.No","Column Name","Record Count","Unique Count","Null Count","Total Count"])
i=1
for col in dfTrace.columns:
    headers.add_row([i,col,dfTrace[col].count(),dfTrace[col].nunique(),
                    dfTrace[col].isnull().sum(),dfTrace[col].count()+dfTrace[col].isnull().sum()])
    i+=1
    
print(headers)

+------+-----------------------------+--------------+--------------+------------+-------------+
| S.No |         Column Name         | Record Count | Unique Count | Null Count | Total Count |
+------+-----------------------------+--------------+--------------+------------+-------------+
|  1   |       transaction_hash      |   1598326    |    156381    |     0      |   1598326   |
|  2   |      transaction_index      |   1598326    |     206      |     0      |   1598326   |
|  3   |      trace_from_address     |   1598326    |     2880     |     0      |   1598326   |
|  4   |       trace_to_address      |   1598326    |     935      |     0      |   1598326   |
|  5   |         trace_value         |   1598326    |    20855     |     0      |   1598326   |
|  6   |         trace_input         |   1598326    |    219587    |     0      |   1598326   |
|  7   |         trace_output        |   1598326    |     4909     |     0      |   1598326   |
|  8   |          trace_gas          |   1598326    |    84592     |     0      |   1598326   |
|  9   |        trace_gas_used       |   1598326    |    11780     |     0      |   1598326   |
|  10  |          subtraces          |   1598326    |      34      |     0      |   1598326   |
|  11  |       block_timestamp       |   1598326    |    69457     |     0      |   1598326   |
|  12  |         block_number        |   1598326    |    69457     |     0      |   1598326   |
|  13  |          block_hash         |   1598326    |    69457     |     0      |   1598326   |
|  14  |        token_address        |   1598326    |     148      |     0      |   1598326   |
|  15  | token_transfer_from_address |   1598326    |     2566     |     0      |   1598326   |
|  16  |  token_transfer_to_address  |   1598326    |    28948     |     0      |   1598326   |
|  17  |     token_transfer_value    |   1598326    |    32176     |     0      |   1598326   |
|  18  |          log_index          |   1598326    |     353      |     0      |   1598326   |
+------+-----------------------------+--------------+--------------+------------+-------------+

In [101]:

dfTrace.drop(['block_timestamp_y',
              'block_number_y',
              'block_hash_y'
             ], axis=1, inplace=True)

In [102]:
dfTrace.columns = ['transaction_hash', 
                   'transaction_index',
                   'trace_from_address',
                   'trace_to_address',
                   'trace_value',
                   'trace_input',
                   'trace_output',
                   'trace_gas',
                   'trace_gas_used',
                   'subtraces',
                   'block_timestamp',
                   'block_number',
                   'block_hash',
                   'token_address',
                   'token_transfer_from_address',
                   'token_transfer_to_address',
                   'token_transfer_value',
                   'log_index'                
                  ]

# Transaction

In [60]:
dfTransaction = pd.read_csv('/Users/rparama/Downloads/Dataset/transactions_2019.csv')
dfTransaction.head()

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (5,11,12) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

                                                hash  nonce  transaction_index                                from_address                                  to_address                 value      gas   gas_price       input  receipt_cumulative_gas_used  receipt_gas_used receipt_contract_address receipt_root  receipt_status            block_timestamp  block_number                                         block_hash
0  0x7a54c44fa7af89bd2552dc3c42bac6b1163e9a8c3f5f...      6                  4  0x9aaccdb8b5577d5a090a90979f40996dc9f68ed9  0x4f2899b122d1d878684b5c8b04de3d8ff5a10767                     0   271616  5000000000  0x3d8705ab                       355616            271616                      NaN          NaN             0.0  2019-11-20 14:13:02+00:00       9227052  0x2e99dd1d5a86bc23923f7ecd385896dec81b94f77eba...
1  0x1740ac84b82e10a8adf53cf07b4cf76808d84dfb4e31...   1524                  0  0x5597ce5678c139a83dc2c98861d77ec5b7567890  0xafed565b31b3163ad80e1b80aab59175bf07c35d    601381412000000000  1600000  1000000000          0x                        21000             21000                      NaN          NaN             1.0  2019-11-20 04:40:10+00:00       9224448  0x46a6811ef192107aa5a4abeddb500bf30a1fa88c194a...
2  0x093fcf99836b5d4a8e28a4e69e25bbdf1c0eef205419...   2264                  2  0x9e3d391cd779b241f97c9c5b7d5e99dc6c23da10  0x282f5ffb3c1d5dce293f6b0cd61419c3afb6d125    610884781000000000  1600000  1000000000          0x                       214260             21000                      NaN          NaN             1.0  2019-11-20 09:15:42+00:00       9225728  0xcb5cc3d86372e6a9f3697d735fbe0e9ebfc32238f3ea...
3  0xffaa13959c32e75d77cd7aff15017f4e0cf24530ca52...  66564                  0  0x0c5466b30b8ead83fe534f96c2f18a308804570d  0x9c0fe699eac35fb17ad5438f04aefd5339e8ae13   1141412045000000000  1600000  1000000000          0x                        21000             21000                      NaN          NaN             1.0  2019-11-20 14:02:48+00:00       9227008  0x996ba9315788195e1d53ae195e26148612b0b565aa65...
4  0x858f45f8a43ec7a26f71e161b40d36695891ebf00305...   1547                  1  0x5597ce5678c139a83dc2c98861d77ec5b7567890  0xbf07da0701b0b2e6ba2446bcdcc13b3e1ada56f8  12395728203000000000  1600000  1000000000          0x                        42000             21000                      NaN          NaN             1.0  2019-11-20 14:53:24+00:00       9227264  0x4fa99293a7fb729185669f27aed0a99e8b1b37668111...

In [105]:
dfETH = pd.merge(dfTrace,dfTransaction, how = 'inner', left_on=['transaction_hash'],right_on=['hash'])
dfETH.head(10)

                                    transaction_hash  transaction_index_x                          trace_from_address                            trace_to_address          trace_value                                        trace_input                                       trace_output  trace_gas  trace_gas_used  subtraces          block_timestamp_x  block_number_x                                       block_hash_x                               token_address                 token_transfer_from_address                   token_transfer_to_address token_transfer_value  log_index                                               hash  nonce  transaction_index_y                                from_address                                  to_address                value     gas   gas_price                                              input  receipt_cumulative_gas_used  receipt_gas_used receipt_contract_address receipt_root  receipt_status          block_timestamp_y  block_number_y                                       block_hash_y
0  0x12d11793515571efff5f876397e714aa4d1cf3b82749...                  7.0  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x51a5c4d6b39b4f789464a9a8e434447764953f92  3600000000000000000                                                 0x                                                 0x     2300.0             0.0          0  2019-11-16 03:48:38+00:00         9197934  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...  0xac55641cbb734bdf6510d1bbd62e240c2409040f  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x94f9e355fe66eeb5bf8b09fbdf493e1f64680f2a            400000000          5  0x12d11793515571efff5f876397e714aa4d1cf3b82749...     84                    7  0x94f9e355fe66eeb5bf8b09fbdf493e1f64680f2a  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  3609022556390977443  160000  1000000000  0xa4ff9c34000000000000000000000000000000000000...                       288741             65926                      NaN          NaN             1.0  2019-11-16 03:48:38+00:00         9197934  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...
1  0x12d11793515571efff5f876397e714aa4d1cf3b82749...                  7.0  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x51a5c4d6b39b4f789464a9a8e434447764953f92  3600000000000000000                                                 0x                                                 0x     2300.0             0.0          0  2019-11-16 03:48:38+00:00         9197934  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...  0xac55641cbb734bdf6510d1bbd62e240c2409040f  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x94f9e355fe66eeb5bf8b09fbdf493e1f64680f2a               902255          8  0x12d11793515571efff5f876397e714aa4d1cf3b82749...     84                    7  0x94f9e355fe66eeb5bf8b09fbdf493e1f64680f2a  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  3609022556390977443  160000  1000000000  0xa4ff9c34000000000000000000000000000000000000...                       288741             65926                      NaN          NaN             1.0  2019-11-16 03:48:38+00:00         9197934  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...
2  0x12d11793515571efff5f876397e714aa4d1cf3b82749...                  7.0  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0xac55641cbb734bdf6510d1bbd62e240c2409040f                    0  0xa9059cbb00000000000000000000000094f9e355fe66...  0x00000000000000000000000000000000000000000000...    78557.0         17277.0          0  2019-11-16 03:48:38+00:00         9197934  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...  0xac55641cbb734bdf6510d1bbd62e240c2409040f  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x94f9e355fe66eeb5bf8b09fbdf493e1f64680f2a            400000000          5  0x12d11793515571efff5f876397e714aa4d1cf3b82749...     84                    7  0x94f9e355fe66eeb5bf8b09fbdf493e1f64680f2a  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  3609022556390977443  160000  1000000000  0xa4ff9c34000000000000000000000000000000000000...                       288741             65926                      NaN          NaN             1.0  2019-11-16 03:48:38+00:00         9197934  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...
3  0x12d11793515571efff5f876397e714aa4d1cf3b82749...                  7.0  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0xac55641cbb734bdf6510d1bbd62e240c2409040f                    0  0xa9059cbb00000000000000000000000094f9e355fe66...  0x00000000000000000000000000000000000000000000...    78557.0         17277.0          0  2019-11-16 03:48:38+00:00         9197934  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...  0xac55641cbb734bdf6510d1bbd62e240c2409040f  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x94f9e355fe66eeb5bf8b09fbdf493e1f64680f2a               902255          8  0x12d11793515571efff5f876397e714aa4d1cf3b82749...     84                    7  0x94f9e355fe66eeb5bf8b09fbdf493e1f64680f2a  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  3609022556390977443  160000  1000000000  0xa4ff9c34000000000000000000000000000000000000...                       288741             65926                      NaN          NaN             1.0  2019-11-16 03:48:38+00:00         9197934  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...
4  0x12d11793515571efff5f876397e714aa4d1cf3b82749...                  7.0  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0xac55641cbb734bdf6510d1bbd62e240c2409040f                    0  0xa9059cbb00000000000000000000000094f9e355fe66...  0x00000000000000000000000000000000000000000000...   115590.0         17277.0          0  2019-11-16 03:48:38+00:00         9197934  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...  0xac55641cbb734bdf6510d1bbd62e240c2409040f  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x94f9e355fe66eeb5bf8b09fbdf493e1f64680f2a            400000000          5  0x12d11793515571efff5f876397e714aa4d1cf3b82749...     84                    7  0x94f9e355fe66eeb5bf8b09fbdf493e1f64680f2a  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  3609022556390977443  160000  1000000000  0xa4ff9c34000000000000000000000000000000000000...                       288741             65926                      NaN          NaN             1.0  2019-11-16 03:48:38+00:00         9197934  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...
5  0x12d11793515571efff5f876397e714aa4d1cf3b82749...                  7.0  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0xac55641cbb734bdf6510d1bbd62e240c2409040f                    0  0xa9059cbb00000000000000000000000094f9e355fe66...  0x00000000000000000000000000000000000000000000...   115590.0         17277.0          0  2019-11-16 03:48:38+00:00         9197934  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...  0xac55641cbb734bdf6510d1bbd62e240c2409040f  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x94f9e355fe66eeb5bf8b09fbdf493e1f64680f2a               902255          8  0x12d11793515571efff5f876397e714aa4d1cf3b82749...     84                    7  0x94f9e355fe66eeb5bf8b09fbdf493e1f64680f2a  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  3609022556390977443  160000  1000000000  0xa4ff9c34000000000000000000000000000000000000...                       288741             65926                      NaN          NaN             1.0  2019-11-16 03:48:38+00:00         9197934  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...
6  0x12d11793515571efff5f876397e714aa4d1cf3b82749...                  7.0  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x92eeb915dafe3803f8a9d12000765c3b6af6d5fd     9022556390977443                                                 0x                                                 0x     2300.0             0.0          0  2019-11-16 03:48:38+00:00         9197934  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...  0xac55641cbb734bdf6510d1bbd62e240c2409040f  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x94f9e355fe66eeb5bf8b09fbdf493e1f64680f2a            400000000          5  0x12d11793515571efff5f876397e714aa4d1cf3b82749...     84                    7  0x94f9e355fe66eeb5bf8b09fbdf493e1f64680f2a  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  3609022556390977443  160000  1000000000  0xa4ff9c34000000000000000000000000000000000000...                       288741             65926                      NaN          NaN             1.0  2019-11-16 03:48:38+00:00         9197934  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...
7  0x12d11793515571efff5f876397e714aa4d1cf3b82749...                  7.0  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x92eeb915dafe3803f8a9d12000765c3b6af6d5fd     9022556390977443                                                 0x                                                 0x     2300.0             0.0          0  2019-11-16 03:48:38+00:00         9197934  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...  0xac55641cbb734bdf6510d1bbd62e240c2409040f  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x94f9e355fe66eeb5bf8b09fbdf493e1f64680f2a               902255          8  0x12d11793515571efff5f876397e714aa4d1cf3b82749...     84                    7  0x94f9e355fe66eeb5bf8b09fbdf493e1f64680f2a  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  3609022556390977443  160000  1000000000  0xa4ff9c34000000000000000000000000000000000000...                       288741             65926                      NaN          NaN             1.0  2019-11-16 03:48:38+00:00         9197934  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...
8  0x12d11793515571efff5f876397e714aa4d1cf3b82749...                  7.0  0x94f9e355fe66eeb5bf8b09fbdf493e1f64680f2a  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  3609022556390977443  0xa4ff9c34000000000000000000000000000000000000...                                                 0x   138472.0        110324.0          4  2019-11-16 03:48:38+00:00         9197934  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...  0xac55641cbb734bdf6510d1bbd62e240c2409040f  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x94f9e355fe66eeb5bf8b09fbdf493e1f64680f2a            400000000          5  0x12d11793515571efff5f876397e714aa4d1cf3b82749...     84                    7  0x94f9e355fe66eeb5bf8b09fbdf493e1f64680f2a  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  3609022556390977443  160000  1000000000  0xa4ff9c34000000000000000000000000000000000000...                       288741             65926                      NaN          NaN             1.0  2019-11-16 03:48:38+00:00         9197934  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...
9  0x12d11793515571efff5f876397e714aa4d1cf3b82749...                  7.0  0x94f9e355fe66eeb5bf8b09fbdf493e1f64680f2a  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  3609022556390977443  0xa4ff9c34000000000000000000000000000000000000...                                                 0x   138472.0        110324.0          4  2019-11-16 03:48:38+00:00         9197934  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...  0xac55641cbb734bdf6510d1bbd62e240c2409040f  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x94f9e355fe66eeb5bf8b09fbdf493e1f64680f2a               902255          8  0x12d11793515571efff5f876397e714aa4d1cf3b82749...     84                    7  0x94f9e355fe66eeb5bf8b09fbdf493e1f64680f2a  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  3609022556390977443  160000  1000000000  0xa4ff9c34000000000000000000000000000000000000...                       288741             65926                      NaN          NaN             1.0  2019-11-16 03:48:38+00:00         9197934  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...

In [106]:
dfETH.shape

(1598326, 35)

In [107]:
headers=PrettyTable(["S.No","Column Name","Record Count","Unique Count","Null Count","Total Count"])
i=1
for col in dfETH.columns:
    headers.add_row([i,col,dfETH[col].count(),dfETH[col].nunique(),
                    dfETH[col].isnull().sum(),dfETH[col].count()+dfETH[col].isnull().sum()])
    i+=1
    
print(headers)

+------+-----------------------------+--------------+--------------+------------+-------------+
| S.No |         Column Name         | Record Count | Unique Count | Null Count | Total Count |
+------+-----------------------------+--------------+--------------+------------+-------------+
|  1   |       transaction_hash      |   1598326    |    156381    |     0      |   1598326   |
|  2   |     transaction_index_x     |   1598326    |     206      |     0      |   1598326   |
|  3   |      trace_from_address     |   1598326    |     2880     |     0      |   1598326   |
|  4   |       trace_to_address      |   1598326    |     935      |     0      |   1598326   |
|  5   |         trace_value         |   1598326    |    20855     |     0      |   1598326   |
|  6   |         trace_input         |   1598326    |    219587    |     0      |   1598326   |
|  7   |         trace_output        |   1598326    |     4909     |     0      |   1598326   |
|  8   |          trace_gas          |   1598326    |    84592     |     0      |   1598326   |
|  9   |        trace_gas_used       |   1598326    |    11780     |     0      |   1598326   |
|  10  |          subtraces          |   1598326    |      34      |     0      |   1598326   |
|  11  |      block_timestamp_x      |   1598326    |    69457     |     0      |   1598326   |
|  12  |        block_number_x       |   1598326    |    69457     |     0      |   1598326   |
|  13  |         block_hash_x        |   1598326    |    69457     |     0      |   1598326   |
|  14  |        token_address        |   1598326    |     148      |     0      |   1598326   |
|  15  | token_transfer_from_address |   1598326    |     2566     |     0      |   1598326   |
|  16  |  token_transfer_to_address  |   1598326    |    28948     |     0      |   1598326   |
|  17  |     token_transfer_value    |   1598326    |    32176     |     0      |   1598326   |
|  18  |          log_index          |   1598326    |     353      |     0      |   1598326   |
|  19  |             hash            |   1598326    |    156381    |     0      |   1598326   |
|  20  |            nonce            |   1598326    |    31684     |     0      |   1598326   |
|  21  |     transaction_index_y     |   1598326    |     206      |     0      |   1598326   |
|  22  |         from_address        |   1598326    |     2658     |     0      |   1598326   |
|  23  |          to_address         |   1598325    |     258      |     1      |   1598326   |
|  24  |            value            |   1598326    |     3889     |     0      |   1598326   |
|  25  |             gas             |   1598326    |     2699     |     0      |   1598326   |
|  26  |          gas_price          |   1598326    |     222      |     0      |   1598326   |
|  27  |            input            |   1598326    |    112435    |     0      |   1598326   |
|  28  | receipt_cumulative_gas_used |   1598326    |    102490    |     0      |   1598326   |
|  29  |       receipt_gas_used      |   1598326    |     8540     |     0      |   1598326   |
|  30  |   receipt_contract_address  |      1       |      1       |  1598325   |   1598326   |
|  31  |         receipt_root        |    689194    |    119917    |   909132   |   1598326   |
|  32  |        receipt_status       |    909132    |      1       |   689194   |   1598326   |
|  33  |      block_timestamp_y      |   1598326    |    69457     |     0      |   1598326   |
|  34  |        block_number_y       |   1598326    |    69457     |     0      |   1598326   |
|  35  |         block_hash_y        |   1598326    |    69457     |     0      |   1598326   |
+------+-----------------------------+--------------+--------------+------------+-------------+

In [110]:

dfETH = dfETH[(dfETH['block_timestamp_x'] == dfETH['block_timestamp_y']) &
              (dfETH['block_number_x'] == dfETH['block_number_y']) &
              (dfETH['block_hash_x'] == dfETH['block_hash_y']) &
              (dfETH['transaction_index_x'] == dfETH['transaction_index_y'])
             ]

In [111]:

dfETH.drop(['block_timestamp_y',
            'block_number_y',
            'block_hash_y',
            'transaction_index_y'
           ], axis=1, inplace=True)

In [112]:
headers=PrettyTable(["S.No","Column Name","Record Count","Unique Count","Null Count","Total Count"])
i=1
for col in dfETH.columns:
    headers.add_row([i,col,dfETH[col].count(),dfETH[col].nunique(),
                    dfETH[col].isnull().sum(),dfETH[col].count()+dfETH[col].isnull().sum()])
    i+=1
    
print(headers)

+------+-----------------------------+--------------+--------------+------------+-------------+
| S.No |         Column Name         | Record Count | Unique Count | Null Count | Total Count |
+------+-----------------------------+--------------+--------------+------------+-------------+
|  1   |       transaction_hash      |   1598326    |    156381    |     0      |   1598326   |
|  2   |     transaction_index_x     |   1598326    |     206      |     0      |   1598326   |
|  3   |      trace_from_address     |   1598326    |     2880     |     0      |   1598326   |
|  4   |       trace_to_address      |   1598326    |     935      |     0      |   1598326   |
|  5   |         trace_value         |   1598326    |    20855     |     0      |   1598326   |
|  6   |         trace_input         |   1598326    |    219587    |     0      |   1598326   |
|  7   |         trace_output        |   1598326    |     4909     |     0      |   1598326   |
|  8   |          trace_gas          |   1598326    |    84592     |     0      |   1598326   |
|  9   |        trace_gas_used       |   1598326    |    11780     |     0      |   1598326   |
|  10  |          subtraces          |   1598326    |      34      |     0      |   1598326   |
|  11  |      block_timestamp_x      |   1598326    |    69457     |     0      |   1598326   |
|  12  |        block_number_x       |   1598326    |    69457     |     0      |   1598326   |
|  13  |         block_hash_x        |   1598326    |    69457     |     0      |   1598326   |
|  14  |        token_address        |   1598326    |     148      |     0      |   1598326   |
|  15  | token_transfer_from_address |   1598326    |     2566     |     0      |   1598326   |
|  16  |  token_transfer_to_address  |   1598326    |    28948     |     0      |   1598326   |
|  17  |     token_transfer_value    |   1598326    |    32176     |     0      |   1598326   |
|  18  |          log_index          |   1598326    |     353      |     0      |   1598326   |
|  19  |             hash            |   1598326    |    156381    |     0      |   1598326   |
|  20  |            nonce            |   1598326    |    31684     |     0      |   1598326   |
|  21  |         from_address        |   1598326    |     2658     |     0      |   1598326   |
|  22  |          to_address         |   1598325    |     258      |     1      |   1598326   |
|  23  |            value            |   1598326    |     3889     |     0      |   1598326   |
|  24  |             gas             |   1598326    |     2699     |     0      |   1598326   |
|  25  |          gas_price          |   1598326    |     222      |     0      |   1598326   |
|  26  |            input            |   1598326    |    112435    |     0      |   1598326   |
|  27  | receipt_cumulative_gas_used |   1598326    |    102490    |     0      |   1598326   |
|  28  |       receipt_gas_used      |   1598326    |     8540     |     0      |   1598326   |
|  29  |   receipt_contract_address  |      1       |      1       |  1598325   |   1598326   |
|  30  |         receipt_root        |    689194    |    119917    |   909132   |   1598326   |
|  31  |        receipt_status       |    909132    |      1       |   689194   |   1598326   |
+------+-----------------------------+--------------+--------------+------------+-------------+

In [113]:
dfETH.columns = ['transaction_hash', 
                   'transaction_index',
                   'trace_from_address',
                   'trace_to_address',
                   'trace_value',
                   'trace_input',
                   'trace_output',
                   'trace_gas',
                   'trace_gas_used',
                   'subtraces',
                   'block_timestamp',
                   'block_number',
                   'block_hash',
                   'token_address',
                   'token_transfer_from_address',
                   'token_transfer_to_address',
                   'token_transfer_value',
                   'log_index',
                   'hash',
                   'nonce',
                   'transaction_from_address',
                   'transaction_to_address',
                   'transaction_value',
                   'transaction_gas',
                   'transaction_gas_price',
                   'transaction_input',
                   'receipt_cumulative_gas_used',
                   'receipt_gas_used',
                   'receipt_contract_address',
                   'receipt_root',
                   'receipt_status'
                   
                  ]

In [114]:
dfETH.head()

                                    transaction_hash  transaction_index                          trace_from_address                            trace_to_address          trace_value                                        trace_input                                       trace_output  trace_gas  trace_gas_used  subtraces            block_timestamp  block_number                                         block_hash                               token_address                 token_transfer_from_address                   token_transfer_to_address token_transfer_value  log_index                                               hash  nonce                    transaction_from_address                      transaction_to_address    transaction_value  transaction_gas  transaction_gas_price                                  transaction_input  receipt_cumulative_gas_used  receipt_gas_used receipt_contract_address receipt_root  receipt_status
0  0x12d11793515571efff5f876397e714aa4d1cf3b82749...                7.0  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x51a5c4d6b39b4f789464a9a8e434447764953f92  3600000000000000000                                                 0x                                                 0x     2300.0             0.0          0  2019-11-16 03:48:38+00:00       9197934  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...  0xac55641cbb734bdf6510d1bbd62e240c2409040f  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x94f9e355fe66eeb5bf8b09fbdf493e1f64680f2a            400000000          5  0x12d11793515571efff5f876397e714aa4d1cf3b82749...     84  0x94f9e355fe66eeb5bf8b09fbdf493e1f64680f2a  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  3609022556390977443           160000             1000000000  0xa4ff9c34000000000000000000000000000000000000...                       288741             65926                      NaN          NaN             1.0
1  0x12d11793515571efff5f876397e714aa4d1cf3b82749...                7.0  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x51a5c4d6b39b4f789464a9a8e434447764953f92  3600000000000000000                                                 0x                                                 0x     2300.0             0.0          0  2019-11-16 03:48:38+00:00       9197934  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...  0xac55641cbb734bdf6510d1bbd62e240c2409040f  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x94f9e355fe66eeb5bf8b09fbdf493e1f64680f2a               902255          8  0x12d11793515571efff5f876397e714aa4d1cf3b82749...     84  0x94f9e355fe66eeb5bf8b09fbdf493e1f64680f2a  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  3609022556390977443           160000             1000000000  0xa4ff9c34000000000000000000000000000000000000...                       288741             65926                      NaN          NaN             1.0
2  0x12d11793515571efff5f876397e714aa4d1cf3b82749...                7.0  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0xac55641cbb734bdf6510d1bbd62e240c2409040f                    0  0xa9059cbb00000000000000000000000094f9e355fe66...  0x00000000000000000000000000000000000000000000...    78557.0         17277.0          0  2019-11-16 03:48:38+00:00       9197934  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...  0xac55641cbb734bdf6510d1bbd62e240c2409040f  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x94f9e355fe66eeb5bf8b09fbdf493e1f64680f2a            400000000          5  0x12d11793515571efff5f876397e714aa4d1cf3b82749...     84  0x94f9e355fe66eeb5bf8b09fbdf493e1f64680f2a  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  3609022556390977443           160000             1000000000  0xa4ff9c34000000000000000000000000000000000000...                       288741             65926                      NaN          NaN             1.0
3  0x12d11793515571efff5f876397e714aa4d1cf3b82749...                7.0  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0xac55641cbb734bdf6510d1bbd62e240c2409040f                    0  0xa9059cbb00000000000000000000000094f9e355fe66...  0x00000000000000000000000000000000000000000000...    78557.0         17277.0          0  2019-11-16 03:48:38+00:00       9197934  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...  0xac55641cbb734bdf6510d1bbd62e240c2409040f  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x94f9e355fe66eeb5bf8b09fbdf493e1f64680f2a               902255          8  0x12d11793515571efff5f876397e714aa4d1cf3b82749...     84  0x94f9e355fe66eeb5bf8b09fbdf493e1f64680f2a  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  3609022556390977443           160000             1000000000  0xa4ff9c34000000000000000000000000000000000000...                       288741             65926                      NaN          NaN             1.0
4  0x12d11793515571efff5f876397e714aa4d1cf3b82749...                7.0  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0xac55641cbb734bdf6510d1bbd62e240c2409040f                    0  0xa9059cbb00000000000000000000000094f9e355fe66...  0x00000000000000000000000000000000000000000000...   115590.0         17277.0          0  2019-11-16 03:48:38+00:00       9197934  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...  0xac55641cbb734bdf6510d1bbd62e240c2409040f  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x94f9e355fe66eeb5bf8b09fbdf493e1f64680f2a            400000000          5  0x12d11793515571efff5f876397e714aa4d1cf3b82749...     84  0x94f9e355fe66eeb5bf8b09fbdf493e1f64680f2a  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  3609022556390977443           160000             1000000000  0xa4ff9c34000000000000000000000000000000000000...                       288741             65926                      NaN          NaN             1.0

# Token

In [65]:
dfToken = pd.read_csv('/Users/rparama/Downloads/Dataset/tokens_all.csv')
dfToken.head()

                                      address symbol          name  decimals total_supply            block_timestamp  block_number                                         block_hash
0  0xd61d2d198903859e85c568da305a1ebfbb69a68f    SER   SeratioCoin       7.0            0  2018-07-19 09:24:26+00:00       6208523  0x9a852e0e6f61d154e5d7091832da5eae9f1da3cf25ea...
1  0x2e63c833d30f7faa5459e03d8322f08a24b0c52a    SER   SeratioCoin       7.0            0  2018-07-19 05:03:44+00:00       6207413  0xe78fab47de91187eaab2f2cc1e7e6e34bc5cd1954515...
2  0x0bba46372cb0de7b5cd23424ffde0d90287991ce    SER   SeratioCoin       7.0            0  2018-07-19 13:14:33+00:00       6209527  0x7c63a370d22f60f7a214b9135427848e002d337d0ac6...
3  0x7c38b41c7170f0a1a5ad82601310bf34265054df    STC  Student Coin       7.0            0  2018-08-24 23:50:50+00:00       6431898  0xe0a18b63bbba940eaf3d5f2bdb863b791545083c4eb6...
4  0x8819a708b46f63bdd4b876230551658a26070f8e    SER   SeratioCoin       7.0            0  2018-07-16 13:55:36+00:00       6191375  0xcebe763eee1697c64444cd33030e2e8b6a5d6a0682df...

In [242]:
dfETH2 = pd.merge(dfETH,dfToken, how = 'inner', left_on=['token_address'],right_on=['address'])
dfETH2.head(10)

                                    transaction_hash  transaction_index                          trace_from_address                            trace_to_address          trace_value                                        trace_input                                       trace_output  trace_gas  trace_gas_used  subtraces          block_timestamp_x  block_number_x                                       block_hash_x                               token_address                 token_transfer_from_address                   token_transfer_to_address token_transfer_value  log_index                                               hash  nonce                    transaction_from_address                      transaction_to_address transaction_value  transaction_gas  transaction_gas_price                                  transaction_input  receipt_cumulative_gas_used  receipt_gas_used receipt_contract_address receipt_root  receipt_status                                     address symbol           name  decimals      total_supply          block_timestamp_y  block_number_y                                       block_hash_y
0  0xcdb66b2f5bb2e22ebe6cb8844a0a6931d0e3d1734455...                0.0  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x92eeb915dafe3803f8a9d12000765c3b6af6d5fd     5250000000000000                                                 0x                                                 0x     2300.0             0.0          0  2019-11-16 03:58:49+00:00         9197987  0x69ef40193e817e181aab1f5d29ecc118ee994d3fa2d0...  0x76d0184cf511788032a74a1fb91146e63f43dd53  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0xb955de52193ccd4a38a61603aad49b22009e9b7c         100000000000          2  0xcdb66b2f5bb2e22ebe6cb8844a0a6931d0e3d1734455...     17  0x975a256221f3d3c10e22c76b143e4333908ea1c3  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a                 0           124210            23000000000  0xcf6ff173000000000000000000000000000000000000...                       124210            124210                      NaN          NaN             1.0  0x76d0184cf511788032a74a1fb91146e63f43dd53    UVC  UniversalCoin       5.0  4000000000000000  2019-10-27 09:51:47+00:00         9067987  0x993075de383faf5ce67fa7067980789f0c2c25516aa5...
1  0xcdb66b2f5bb2e22ebe6cb8844a0a6931d0e3d1734455...                0.0  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x92eeb915dafe3803f8a9d12000765c3b6af6d5fd     5250000000000000                                                 0x                                                 0x     2300.0             0.0          0  2019-11-16 03:58:49+00:00         9197987  0x69ef40193e817e181aab1f5d29ecc118ee994d3fa2d0...  0x76d0184cf511788032a74a1fb91146e63f43dd53  0x975a256221f3d3c10e22c76b143e4333908ea1c3  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a         100000000000          0  0xcdb66b2f5bb2e22ebe6cb8844a0a6931d0e3d1734455...     17  0x975a256221f3d3c10e22c76b143e4333908ea1c3  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a                 0           124210            23000000000  0xcf6ff173000000000000000000000000000000000000...                       124210            124210                      NaN          NaN             1.0  0x76d0184cf511788032a74a1fb91146e63f43dd53    UVC  UniversalCoin       5.0  4000000000000000  2019-10-27 09:51:47+00:00         9067987  0x993075de383faf5ce67fa7067980789f0c2c25516aa5...
2  0xcdb66b2f5bb2e22ebe6cb8844a0a6931d0e3d1734455...                0.0  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x975a256221f3d3c10e22c76b143e4333908ea1c3  2094750000000000000                                                 0x                                                 0x     2300.0             0.0          0  2019-11-16 03:58:49+00:00         9197987  0x69ef40193e817e181aab1f5d29ecc118ee994d3fa2d0...  0x76d0184cf511788032a74a1fb91146e63f43dd53  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0xb955de52193ccd4a38a61603aad49b22009e9b7c         100000000000          2  0xcdb66b2f5bb2e22ebe6cb8844a0a6931d0e3d1734455...     17  0x975a256221f3d3c10e22c76b143e4333908ea1c3  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a                 0           124210            23000000000  0xcf6ff173000000000000000000000000000000000000...                       124210            124210                      NaN          NaN             1.0  0x76d0184cf511788032a74a1fb91146e63f43dd53    UVC  UniversalCoin       5.0  4000000000000000  2019-10-27 09:51:47+00:00         9067987  0x993075de383faf5ce67fa7067980789f0c2c25516aa5...
3  0xcdb66b2f5bb2e22ebe6cb8844a0a6931d0e3d1734455...                0.0  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x975a256221f3d3c10e22c76b143e4333908ea1c3  2094750000000000000                                                 0x                                                 0x     2300.0             0.0          0  2019-11-16 03:58:49+00:00         9197987  0x69ef40193e817e181aab1f5d29ecc118ee994d3fa2d0...  0x76d0184cf511788032a74a1fb91146e63f43dd53  0x975a256221f3d3c10e22c76b143e4333908ea1c3  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a         100000000000          0  0xcdb66b2f5bb2e22ebe6cb8844a0a6931d0e3d1734455...     17  0x975a256221f3d3c10e22c76b143e4333908ea1c3  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a                 0           124210            23000000000  0xcf6ff173000000000000000000000000000000000000...                       124210            124210                      NaN          NaN             1.0  0x76d0184cf511788032a74a1fb91146e63f43dd53    UVC  UniversalCoin       5.0  4000000000000000  2019-10-27 09:51:47+00:00         9067987  0x993075de383faf5ce67fa7067980789f0c2c25516aa5...
4  0xcdb66b2f5bb2e22ebe6cb8844a0a6931d0e3d1734455...                0.0  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x76d0184cf511788032a74a1fb91146e63f43dd53                    0  0x23b872dd000000000000000000000000975a256221f3...  0x00000000000000000000000000000000000000000000...    96913.0         21218.0          0  2019-11-16 03:58:49+00:00         9197987  0x69ef40193e817e181aab1f5d29ecc118ee994d3fa2d0...  0x76d0184cf511788032a74a1fb91146e63f43dd53  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0xb955de52193ccd4a38a61603aad49b22009e9b7c         100000000000          2  0xcdb66b2f5bb2e22ebe6cb8844a0a6931d0e3d1734455...     17  0x975a256221f3d3c10e22c76b143e4333908ea1c3  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a                 0           124210            23000000000  0xcf6ff173000000000000000000000000000000000000...                       124210            124210                      NaN          NaN             1.0  0x76d0184cf511788032a74a1fb91146e63f43dd53    UVC  UniversalCoin       5.0  4000000000000000  2019-10-27 09:51:47+00:00         9067987  0x993075de383faf5ce67fa7067980789f0c2c25516aa5...
5  0xcdb66b2f5bb2e22ebe6cb8844a0a6931d0e3d1734455...                0.0  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x76d0184cf511788032a74a1fb91146e63f43dd53                    0  0x23b872dd000000000000000000000000975a256221f3...  0x00000000000000000000000000000000000000000000...    96913.0         21218.0          0  2019-11-16 03:58:49+00:00         9197987  0x69ef40193e817e181aab1f5d29ecc118ee994d3fa2d0...  0x76d0184cf511788032a74a1fb91146e63f43dd53  0x975a256221f3d3c10e22c76b143e4333908ea1c3  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a         100000000000          0  0xcdb66b2f5bb2e22ebe6cb8844a0a6931d0e3d1734455...     17  0x975a256221f3d3c10e22c76b143e4333908ea1c3  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a                 0           124210            23000000000  0xcf6ff173000000000000000000000000000000000000...                       124210            124210                      NaN          NaN             1.0  0x76d0184cf511788032a74a1fb91146e63f43dd53    UVC  UniversalCoin       5.0  4000000000000000  2019-10-27 09:51:47+00:00         9067987  0x993075de383faf5ce67fa7067980789f0c2c25516aa5...
6  0xcdb66b2f5bb2e22ebe6cb8844a0a6931d0e3d1734455...                0.0  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0xac55641cbb734bdf6510d1bbd62e240c2409040f                    0  0xa9059cbb000000000000000000000000975a256221f3...  0x00000000000000000000000000000000000000000000...    19220.0         17277.0          0  2019-11-16 03:58:49+00:00         9197987  0x69ef40193e817e181aab1f5d29ecc118ee994d3fa2d0...  0x76d0184cf511788032a74a1fb91146e63f43dd53  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0xb955de52193ccd4a38a61603aad49b22009e9b7c         100000000000          2  0xcdb66b2f5bb2e22ebe6cb8844a0a6931d0e3d1734455...     17  0x975a256221f3d3c10e22c76b143e4333908ea1c3  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a                 0           124210            23000000000  0xcf6ff173000000000000000000000000000000000000...                       124210            124210                      NaN          NaN             1.0  0x76d0184cf511788032a74a1fb91146e63f43dd53    UVC  UniversalCoin       5.0  4000000000000000  2019-10-27 09:51:47+00:00         9067987  0x993075de383faf5ce67fa7067980789f0c2c25516aa5...
7  0xcdb66b2f5bb2e22ebe6cb8844a0a6931d0e3d1734455...                0.0  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0xac55641cbb734bdf6510d1bbd62e240c2409040f                    0  0xa9059cbb000000000000000000000000975a256221f3...  0x00000000000000000000000000000000000000000000...    19220.0         17277.0          0  2019-11-16 03:58:49+00:00         9197987  0x69ef40193e817e181aab1f5d29ecc118ee994d3fa2d0...  0x76d0184cf511788032a74a1fb91146e63f43dd53  0x975a256221f3d3c10e22c76b143e4333908ea1c3  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a         100000000000          0  0xcdb66b2f5bb2e22ebe6cb8844a0a6931d0e3d1734455...     17  0x975a256221f3d3c10e22c76b143e4333908ea1c3  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a                 0           124210            23000000000  0xcf6ff173000000000000000000000000000000000000...                       124210            124210                      NaN          NaN             1.0  0x76d0184cf511788032a74a1fb91146e63f43dd53    UVC  UniversalCoin       5.0  4000000000000000  2019-10-27 09:51:47+00:00         9067987  0x993075de383faf5ce67fa7067980789f0c2c25516aa5...
8  0xcdb66b2f5bb2e22ebe6cb8844a0a6931d0e3d1734455...                0.0  0x975a256221f3d3c10e22c76b143e4333908ea1c3  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a                    0  0xcf6ff173000000000000000000000000000000000000...                                                 0x   100890.0        100890.0          5  2019-11-16 03:58:49+00:00         9197987  0x69ef40193e817e181aab1f5d29ecc118ee994d3fa2d0...  0x76d0184cf511788032a74a1fb91146e63f43dd53  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0xb955de52193ccd4a38a61603aad49b22009e9b7c         100000000000          2  0xcdb66b2f5bb2e22ebe6cb8844a0a6931d0e3d1734455...     17  0x975a256221f3d3c10e22c76b143e4333908ea1c3  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a                 0           124210            23000000000  0xcf6ff173000000000000000000000000000000000000...                       124210            124210                      NaN          NaN             1.0  0x76d0184cf511788032a74a1fb91146e63f43dd53    UVC  UniversalCoin       5.0  4000000000000000  2019-10-27 09:51:47+00:00         9067987  0x993075de383faf5ce67fa7067980789f0c2c25516aa5...
9  0xcdb66b2f5bb2e22ebe6cb8844a0a6931d0e3d1734455...                0.0  0x975a256221f3d3c10e22c76b143e4333908ea1c3  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a                    0  0xcf6ff173000000000000000000000000000000000000...                                                 0x   100890.0        100890.0          5  2019-11-16 03:58:49+00:00         9197987  0x69ef40193e817e181aab1f5d29ecc118ee994d3fa2d0...  0x76d0184cf511788032a74a1fb91146e63f43dd53  0x975a256221f3d3c10e22c76b143e4333908ea1c3  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a         100000000000          0  0xcdb66b2f5bb2e22ebe6cb8844a0a6931d0e3d1734455...     17  0x975a256221f3d3c10e22c76b143e4333908ea1c3  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a                 0           124210            23000000000  0xcf6ff173000000000000000000000000000000000000...                       124210            124210                      NaN          NaN             1.0  0x76d0184cf511788032a74a1fb91146e63f43dd53    UVC  UniversalCoin       5.0  4000000000000000  2019-10-27 09:51:47+00:00         9067987  0x993075de383faf5ce67fa7067980789f0c2c25516aa5...

In [244]:
dfETH2.columns

Index(['transaction_hash', 'transaction_index', 'trace_from_address', 'trace_to_address', 'trace_value', 'trace_input', 'trace_output', 'trace_gas', 'trace_gas_used', 'subtraces', 'block_timestamp_x', 'block_number_x', 'block_hash_x', 'token_address', 'token_transfer_from_address', 'token_transfer_to_address', 'token_transfer_value', 'log_index', 'hash', 'nonce', 'transaction_from_address', 'transaction_to_address', 'transaction_value', 'transaction_gas', 'transaction_gas_price', 'transaction_input', 'receipt_cumulative_gas_used', 'receipt_gas_used', 'receipt_contract_address', 'receipt_root', 'receipt_status', 'address', 'symbol', 'name', 'decimals', 'total_supply', 'block_timestamp_y', 'block_number_y', 'block_hash_y'], dtype='object')

In [220]:
headers=PrettyTable(["S.No","Column Name","Record Count","Unique Count","Null Count","Total Count"])
i=1
for col in dfETH2.columns:
    headers.add_row([i,col,dfETH2[col].count(),dfETH2[col].nunique(),
                    dfETH2[col].isnull().sum(),dfETH2[col].count()+dfETH2[col].isnull().sum()])
    i+=1
    
print(headers)

+------+-----------------------------+--------------+--------------+------------+-------------+
| S.No |         Column Name         | Record Count | Unique Count | Null Count | Total Count |
+------+-----------------------------+--------------+--------------+------------+-------------+
|  1   |       transaction_hash      |   1085936    |    81848     |     0      |   1085936   |
|  2   |      transaction_index      |   1085936    |     203      |     0      |   1085936   |
|  3   |      trace_from_address     |   1085936    |     2173     |     0      |   1085936   |
|  4   |       trace_to_address      |   1085936    |     455      |     0      |   1085936   |
|  5   |         trace_value         |   1085936    |     2508     |     0      |   1085936   |
|  6   |         trace_input         |   1085936    |    95195     |     0      |   1085936   |
|  7   |         trace_output        |   1085936    |     4802     |     0      |   1085936   |
|  8   |          trace_gas          |   1085936    |    81785     |     0      |   1085936   |
|  9   |        trace_gas_used       |   1085936    |    11107     |     0      |   1085936   |
|  10  |          subtraces          |   1085936    |      31      |     0      |   1085936   |
|  11  |      block_timestamp_x      |   1085936    |    35117     |     0      |   1085936   |
|  12  |        block_number_x       |   1085936    |    35117     |     0      |   1085936   |
|  13  |         block_hash_x        |   1085936    |    35117     |     0      |   1085936   |
|  14  |        token_address        |   1085936    |      39      |     0      |   1085936   |
|  15  | token_transfer_from_address |   1085936    |     1965     |     0      |   1085936   |
|  16  |  token_transfer_to_address  |   1085936    |    25547     |     0      |   1085936   |
|  17  |     token_transfer_value    |   1085936    |    11616     |     0      |   1085936   |
|  18  |          log_index          |   1085936    |     241      |     0      |   1085936   |
|  19  |             hash            |   1085936    |    81848     |     0      |   1085936   |
|  20  |            nonce            |   1085936    |    31443     |     0      |   1085936   |
|  21  |   transaction_from_address  |   1085936    |     2099     |     0      |   1085936   |
|  22  |    transaction_to_address   |   1085935    |      88      |     1      |   1085936   |
|  23  |      transaction_value      |   1085936    |     348      |     0      |   1085936   |
|  24  |       transaction_gas       |   1085936    |     1544     |     0      |   1085936   |
|  25  |    transaction_gas_price    |   1085936    |     169      |     0      |   1085936   |
|  26  |      transaction_input      |   1085936    |    51440     |     0      |   1085936   |
|  27  | receipt_cumulative_gas_used |   1085936    |    58572     |     0      |   1085936   |
|  28  |       receipt_gas_used      |   1085936    |     7571     |     0      |   1085936   |
|  29  |   receipt_contract_address  |      1       |      1       |  1085935   |   1085936   |
|  30  |         receipt_root        |    456214    |    55051     |   629722   |   1085936   |
|  31  |        receipt_status       |    629722    |      1       |   456214   |   1085936   |
|  32  |           address           |   1085936    |      39      |     0      |   1085936   |
|  33  |            symbol           |   1085798    |      35      |    138     |   1085936   |
|  34  |             name            |   1085798    |      31      |    138     |   1085936   |
|  35  |           decimals          |   1085893    |      11      |     43     |   1085936   |
|  36  |         total_supply        |   1085936    |      32      |     0      |   1085936   |
|  37  |      block_timestamp_y      |   1085936    |      39      |     0      |   1085936   |
|  38  |        block_number_y       |   1085936    |      39      |     0      |   1085936   |
|  39  |         block_hash_y        |   1085936    |      39      |     0      |   1085936   |
+------+-----------------------------+--------------+--------------+------------+-------------+

In [245]:
dfETH2.columns = ['transaction_hash', 
                   'transaction_index',
                   'trace_from_address',
                   'trace_to_address',
                   'trace_value',
                   'trace_input',
                   'trace_output',
                   'trace_gas',
                   'trace_gas_used',
                   'subtraces',
                   'block_timestamp',
                   'block_number',
                   'block_hash',
                   'token_transfer_address',
                   'token_transfer_from_address',
                   'token_transfer_to_address',
                   'token_transfer_value',
                   'log_index',
                   'hash',
                   'nonce',
                   'transaction_from_address',
                   'transaction_to_address',
                   'transaction_value',
                   'transaction_gas',
                   'transaction_gas_price',
                   'transaction_input',
                   'receipt_cumulative_gas_used',
                   'receipt_gas_used',
                   'receipt_contract_address',
                   'receipt_root',
                   'receipt_status',
                  'token_address',
                  'token_symbol',
                  'token_name',
                  'token_decimals',
                  'token_total_supply',
                  'block_timestamp_y',
                  'block_number_y',
                  'block_hash_y'
                  ]

In [247]:
dfETH2.drop(['block_timestamp_y',
            'block_number_y',
            'block_hash_y'
           ], axis=1, inplace=True)

In [248]:
headers=PrettyTable(["S.No","Column Name","Record Count","Unique Count","Null Count","Total Count"])
i=1
for col in dfETH2.columns:
    headers.add_row([i,col,dfETH2[col].count(),dfETH2[col].nunique(),
                    dfETH2[col].isnull().sum(),dfETH2[col].count()+dfETH2[col].isnull().sum()])
    i+=1
    
print(headers)

+------+-----------------------------+--------------+--------------+------------+-------------+
| S.No |         Column Name         | Record Count | Unique Count | Null Count | Total Count |
+------+-----------------------------+--------------+--------------+------------+-------------+
|  1   |       transaction_hash      |   1085936    |    81848     |     0      |   1085936   |
|  2   |      transaction_index      |   1085936    |     203      |     0      |   1085936   |
|  3   |      trace_from_address     |   1085936    |     2173     |     0      |   1085936   |
|  4   |       trace_to_address      |   1085936    |     455      |     0      |   1085936   |
|  5   |         trace_value         |   1085936    |     2508     |     0      |   1085936   |
|  6   |         trace_input         |   1085936    |    95195     |     0      |   1085936   |
|  7   |         trace_output        |   1085936    |     4802     |     0      |   1085936   |
|  8   |          trace_gas          |   1085936    |    81785     |     0      |   1085936   |
|  9   |        trace_gas_used       |   1085936    |    11107     |     0      |   1085936   |
|  10  |          subtraces          |   1085936    |      31      |     0      |   1085936   |
|  11  |       block_timestamp       |   1085936    |    35117     |     0      |   1085936   |
|  12  |         block_number        |   1085936    |    35117     |     0      |   1085936   |
|  13  |          block_hash         |   1085936    |    35117     |     0      |   1085936   |
|  14  |    token_transfer_address   |   1085936    |      39      |     0      |   1085936   |
|  15  | token_transfer_from_address |   1085936    |     1965     |     0      |   1085936   |
|  16  |  token_transfer_to_address  |   1085936    |    25547     |     0      |   1085936   |
|  17  |     token_transfer_value    |   1085936    |    11616     |     0      |   1085936   |
|  18  |          log_index          |   1085936    |     241      |     0      |   1085936   |
|  19  |             hash            |   1085936    |    81848     |     0      |   1085936   |
|  20  |            nonce            |   1085936    |    31443     |     0      |   1085936   |
|  21  |   transaction_from_address  |   1085936    |     2099     |     0      |   1085936   |
|  22  |    transaction_to_address   |   1085935    |      88      |     1      |   1085936   |
|  23  |      transaction_value      |   1085936    |     348      |     0      |   1085936   |
|  24  |       transaction_gas       |   1085936    |     1544     |     0      |   1085936   |
|  25  |    transaction_gas_price    |   1085936    |     169      |     0      |   1085936   |
|  26  |      transaction_input      |   1085936    |    51440     |     0      |   1085936   |
|  27  | receipt_cumulative_gas_used |   1085936    |    58572     |     0      |   1085936   |
|  28  |       receipt_gas_used      |   1085936    |     7571     |     0      |   1085936   |
|  29  |   receipt_contract_address  |      1       |      1       |  1085935   |   1085936   |
|  30  |         receipt_root        |    456214    |    55051     |   629722   |   1085936   |
|  31  |        receipt_status       |    629722    |      1       |   456214   |   1085936   |
|  32  |        token_address        |   1085936    |      39      |     0      |   1085936   |
|  33  |         token_symbol        |   1085798    |      35      |    138     |   1085936   |
|  34  |          token_name         |   1085798    |      31      |    138     |   1085936   |
|  35  |        token_decimals       |   1085893    |      11      |     43     |   1085936   |
|  36  |      token_total_supply     |   1085936    |      32      |     0      |   1085936   |
+------+-----------------------------+--------------+--------------+------------+-------------+

# Contract

In [184]:
dfContract = pd.read_csv('/Users/rparama/Downloads/Dataset/contracts_2019.csv')
dfContract.head()

                                      address                                           bytecode                                 function_sighashes  is_erc20  is_erc721            block_timestamp  block_Date  block_number                                         block_hash
0  0xd605f0085e66d741b53b1252189cfa0ee66c6427  0x608060405234801561001057600080fd5b5060043610...                                                 []     False      False  2019-09-26 22:31:46+00:00  2019-09-26       8867593  0x6ebfa0bc298e896533a0b5515d890e60df95565340ac...
1  0x67b2a2a134c937e4d4082a955c740532d5f8a0f6  0x60606040526004361061013a5763ffffffff60e06002...  ['0x06fdde03', '0x09974386', '0x164aac25', '0x...     False      False  2019-09-26 18:51:43+00:00  2019-09-26       8866631  0x70a9684d97f2df6f4a6be792b566414941f96d5beedc...
2  0xf92a98f754b9c228bee3b39d1a80ab266c30a496  0x60606040526004361061013a5763ffffffff60e06002...  ['0x06fdde03', '0x09974386', '0x164aac25', '0x...     False      False  2019-09-26 19:43:56+00:00  2019-09-26       8866887  0x129ae3f2eea225e5e51c2313161e1f494a9c3cc5740f...
3  0x6b8c700330afe0d4bc5c5458acbdb95ed83ee921  0x60606040526004361061012f5763ffffffff60e06002...  ['0x06fdde03', '0x09974386', '0x164aac25', '0x...     False      False  2019-09-26 20:47:53+00:00  2019-09-26       8867137  0x9c12fa8d1d78ec4e0ec43439b814be14a318dd4f887f...
4  0x27722d33ca86655ef3d1aff872bc18411b5f9451  0x60606040526004361061012f5763ffffffff60e06002...  ['0x06fdde03', '0x09974386', '0x164aac25', '0x...     False      False  2019-09-26 20:24:14+00:00  2019-09-26       8867042  0x513b01833532b7e97cef93e85750f8b80ecc883b5065...

In [251]:

contract_from = pd.merge(dfETH2,dfContract, how = 'inner', left_on=['trace_from_address'],right_on=['address'])

In [252]:
contract_from.shape

(517883, 45)

In [253]:
contract_from.head()

                                    transaction_hash  transaction_index                          trace_from_address                            trace_to_address        trace_value                                        trace_input                                       trace_output  trace_gas  trace_gas_used  subtraces          block_timestamp_x  block_number_x                                       block_hash_x                      token_transfer_address                 token_transfer_from_address                   token_transfer_to_address token_transfer_value  log_index                                               hash  nonce                    transaction_from_address                      transaction_to_address    transaction_value  transaction_gas  transaction_gas_price transaction_input  receipt_cumulative_gas_used  receipt_gas_used receipt_contract_address receipt_root  receipt_status                               token_address token_symbol token_name  token_decimals token_total_supply                                     address                                           bytecode                                 function_sighashes  is_erc20  is_erc721          block_timestamp_y  block_Date  block_number_y                                       block_hash_y
0  0x3c2a709cee3a943c4c16fbeeaf3e84c38f7c937a47e2...                7.0  0x09aced531359ceffad9759a9252e1d82e3557eb2  0xf5269caa54f1f776dd996db35992d599e14d8a3b                  0  0xfde9cded000000000000000000000000000000000000...  0x00000000000000000000000000000000000000000000...   301428.0          3279.0          0  2019-11-16 01:09:22+00:00         9197228  0x6f6ac9e905b3f0c8f38d64e569efbe30838f90bad3b4...  0xa4d3a7b00056cc5d8206b3b2983bfe0c107d90da  0x0000000000000000000000000000000000000000  0x899fcb4950410ece13a916781c9a339c191ba1b9   468063950110049213          4  0x3c2a709cee3a943c4c16fbeeaf3e84c38f7c937a47e2...     85  0x899fcb4950410ece13a916781c9a339c191ba1b9  0xf5269caa54f1f776dd996db35992d599e14d8a3b  1000000000000000000           350000             2000000000                0x                       341603            194603                      NaN          NaN             1.0  0xa4d3a7b00056cc5d8206b3b2983bfe0c107d90da          MET  Metronome            18.0                  0  0x09aced531359ceffad9759a9252e1d82e3557eb2  0x6080604052600436106100985763ffffffff7c010000...  ['0x2af4c31e', '0x378252f2', '0x50b48c5e', '0x...     False      False  2019-06-24 21:25:13+00:00  2019-06-24         8285384  0x315a86187579161f09a564049868d881347105425321...
1  0x3c2a709cee3a943c4c16fbeeaf3e84c38f7c937a47e2...                7.0  0x09aced531359ceffad9759a9252e1d82e3557eb2  0xf5269caa54f1f776dd996db35992d599e14d8a3b                  0                                         0x496a698d  0x00000000000000000000000000000000000000000000...   307201.0          3324.0          0  2019-11-16 01:09:22+00:00         9197228  0x6f6ac9e905b3f0c8f38d64e569efbe30838f90bad3b4...  0xa4d3a7b00056cc5d8206b3b2983bfe0c107d90da  0x0000000000000000000000000000000000000000  0x899fcb4950410ece13a916781c9a339c191ba1b9   468063950110049213          4  0x3c2a709cee3a943c4c16fbeeaf3e84c38f7c937a47e2...     85  0x899fcb4950410ece13a916781c9a339c191ba1b9  0xf5269caa54f1f776dd996db35992d599e14d8a3b  1000000000000000000           350000             2000000000                0x                       341603            194603                      NaN          NaN             1.0  0xa4d3a7b00056cc5d8206b3b2983bfe0c107d90da          MET  Metronome            18.0                  0  0x09aced531359ceffad9759a9252e1d82e3557eb2  0x6080604052600436106100985763ffffffff7c010000...  ['0x2af4c31e', '0x378252f2', '0x50b48c5e', '0x...     False      False  2019-06-24 21:25:13+00:00  2019-06-24         8285384  0x315a86187579161f09a564049868d881347105425321...
2  0x3c2a709cee3a943c4c16fbeeaf3e84c38f7c937a47e2...                7.0  0x09aced531359ceffad9759a9252e1d82e3557eb2  0xf5269caa54f1f776dd996db35992d599e14d8a3b                  0                                         0x21288400  0x00000000000000000000000000000000000000000000...   309694.0           689.0          0  2019-11-16 01:09:22+00:00         9197228  0x6f6ac9e905b3f0c8f38d64e569efbe30838f90bad3b4...  0xa4d3a7b00056cc5d8206b3b2983bfe0c107d90da  0x0000000000000000000000000000000000000000  0x899fcb4950410ece13a916781c9a339c191ba1b9   468063950110049213          4  0x3c2a709cee3a943c4c16fbeeaf3e84c38f7c937a47e2...     85  0x899fcb4950410ece13a916781c9a339c191ba1b9  0xf5269caa54f1f776dd996db35992d599e14d8a3b  1000000000000000000           350000             2000000000                0x                       341603            194603                      NaN          NaN             1.0  0xa4d3a7b00056cc5d8206b3b2983bfe0c107d90da          MET  Metronome            18.0                  0  0x09aced531359ceffad9759a9252e1d82e3557eb2  0x6080604052600436106100985763ffffffff7c010000...  ['0x2af4c31e', '0x378252f2', '0x50b48c5e', '0x...     False      False  2019-06-24 21:25:13+00:00  2019-06-24         8285384  0x315a86187579161f09a564049868d881347105425321...
3  0x3c2a709cee3a943c4c16fbeeaf3e84c38f7c937a47e2...                7.0  0x09aced531359ceffad9759a9252e1d82e3557eb2  0x567eebb6397cc8345e5a7eae288994bf45fdf85b  65497181753650651                                         0x7679a816                                                 0x   284651.0          4874.0          1  2019-11-16 01:09:22+00:00         9197228  0x6f6ac9e905b3f0c8f38d64e569efbe30838f90bad3b4...  0xa4d3a7b00056cc5d8206b3b2983bfe0c107d90da  0x0000000000000000000000000000000000000000  0x899fcb4950410ece13a916781c9a339c191ba1b9   468063950110049213          4  0x3c2a709cee3a943c4c16fbeeaf3e84c38f7c937a47e2...     85  0x899fcb4950410ece13a916781c9a339c191ba1b9  0xf5269caa54f1f776dd996db35992d599e14d8a3b  1000000000000000000           350000             2000000000                0x                       341603            194603                      NaN          NaN             1.0  0xa4d3a7b00056cc5d8206b3b2983bfe0c107d90da          MET  Metronome            18.0                  0  0x09aced531359ceffad9759a9252e1d82e3557eb2  0x6080604052600436106100985763ffffffff7c010000...  ['0x2af4c31e', '0x378252f2', '0x50b48c5e', '0x...     False      False  2019-06-24 21:25:13+00:00  2019-06-24         8285384  0x315a86187579161f09a564049868d881347105425321...
4  0xfcb065dda0ac9a55bda686b6ba17a4589510198160de...                4.0  0x09aced531359ceffad9759a9252e1d82e3557eb2  0xf5269caa54f1f776dd996db35992d599e14d8a3b                  0                                         0x496a698d  0x00000000000000000000000000000000000000000000...   307201.0          3324.0          0  2019-11-12 00:04:18+00:00         9170672  0xc29f78fc6b752ff54df4206d772dc87747ac0f16e198...  0xa4d3a7b00056cc5d8206b3b2983bfe0c107d90da  0x0000000000000000000000000000000000000000  0x899fcb4950410ece13a916781c9a339c191ba1b9   468063950110049213          4  0xfcb065dda0ac9a55bda686b6ba17a4589510198160de...     75  0x899fcb4950410ece13a916781c9a339c191ba1b9  0xf5269caa54f1f776dd996db35992d599e14d8a3b   500000000000000000           350000             2000000000                0x                       273929            189929                      NaN          NaN             1.0  0xa4d3a7b00056cc5d8206b3b2983bfe0c107d90da          MET  Metronome            18.0                  0  0x09aced531359ceffad9759a9252e1d82e3557eb2  0x6080604052600436106100985763ffffffff7c010000...  ['0x2af4c31e', '0x378252f2', '0x50b48c5e', '0x...     False      False  2019-06-24 21:25:13+00:00  2019-06-24         8285384  0x315a86187579161f09a564049868d881347105425321...

In [254]:
contract_from.address.nunique()

62

In [255]:
contract_to = pd.merge(dfETH2,dfContract, how = 'inner', left_on=['trace_to_address'],right_on=['address'])

In [256]:
contract_to.shape

(445699, 45)

In [257]:
contract_to.head()

                                    transaction_hash  transaction_index                          trace_from_address                            trace_to_address trace_value                                        trace_input                                       trace_output  trace_gas  trace_gas_used  subtraces          block_timestamp_x  block_number_x                                       block_hash_x                      token_transfer_address                 token_transfer_from_address                   token_transfer_to_address token_transfer_value  log_index                                               hash  nonce                    transaction_from_address                      transaction_to_address transaction_value  transaction_gas  transaction_gas_price                                  transaction_input  receipt_cumulative_gas_used  receipt_gas_used receipt_contract_address receipt_root  receipt_status                               token_address token_symbol     token_name  token_decimals token_total_supply                                     address                                           bytecode                                 function_sighashes  is_erc20  is_erc721          block_timestamp_y  block_Date  block_number_y                                       block_hash_y
0  0xcdb66b2f5bb2e22ebe6cb8844a0a6931d0e3d1734455...                0.0  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x76d0184cf511788032a74a1fb91146e63f43dd53           0  0x23b872dd000000000000000000000000975a256221f3...  0x00000000000000000000000000000000000000000000...    96913.0         21218.0          0  2019-11-16 03:58:49+00:00         9197987  0x69ef40193e817e181aab1f5d29ecc118ee994d3fa2d0...  0x76d0184cf511788032a74a1fb91146e63f43dd53  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0xb955de52193ccd4a38a61603aad49b22009e9b7c         100000000000          2  0xcdb66b2f5bb2e22ebe6cb8844a0a6931d0e3d1734455...     17  0x975a256221f3d3c10e22c76b143e4333908ea1c3  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a                 0           124210            23000000000  0xcf6ff173000000000000000000000000000000000000...                       124210            124210                      NaN          NaN             1.0  0x76d0184cf511788032a74a1fb91146e63f43dd53          UVC  UniversalCoin             5.0   4000000000000000  0x76d0184cf511788032a74a1fb91146e63f43dd53  0x6080604052600436106100fc576000357c0100000000...  ['0x06fdde03', '0x095ea7b3', '0x18160ddd', '0x...      True      False  2019-10-27 09:51:47+00:00  2019-10-27         9067987  0x993075de383faf5ce67fa7067980789f0c2c25516aa5...
1  0xcdb66b2f5bb2e22ebe6cb8844a0a6931d0e3d1734455...                0.0  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x76d0184cf511788032a74a1fb91146e63f43dd53           0  0x23b872dd000000000000000000000000975a256221f3...  0x00000000000000000000000000000000000000000000...    96913.0         21218.0          0  2019-11-16 03:58:49+00:00         9197987  0x69ef40193e817e181aab1f5d29ecc118ee994d3fa2d0...  0x76d0184cf511788032a74a1fb91146e63f43dd53  0x975a256221f3d3c10e22c76b143e4333908ea1c3  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a         100000000000          0  0xcdb66b2f5bb2e22ebe6cb8844a0a6931d0e3d1734455...     17  0x975a256221f3d3c10e22c76b143e4333908ea1c3  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a                 0           124210            23000000000  0xcf6ff173000000000000000000000000000000000000...                       124210            124210                      NaN          NaN             1.0  0x76d0184cf511788032a74a1fb91146e63f43dd53          UVC  UniversalCoin             5.0   4000000000000000  0x76d0184cf511788032a74a1fb91146e63f43dd53  0x6080604052600436106100fc576000357c0100000000...  ['0x06fdde03', '0x095ea7b3', '0x18160ddd', '0x...      True      False  2019-10-27 09:51:47+00:00  2019-10-27         9067987  0x993075de383faf5ce67fa7067980789f0c2c25516aa5...
2  0xcdb66b2f5bb2e22ebe6cb8844a0a6931d0e3d1734455...                0.0  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x76d0184cf511788032a74a1fb91146e63f43dd53           0  0xa9059cbb000000000000000000000000b955de52193c...  0x00000000000000000000000000000000000000000000...    64732.0         17580.0          0  2019-11-16 03:58:49+00:00         9197987  0x69ef40193e817e181aab1f5d29ecc118ee994d3fa2d0...  0x76d0184cf511788032a74a1fb91146e63f43dd53  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0xb955de52193ccd4a38a61603aad49b22009e9b7c         100000000000          2  0xcdb66b2f5bb2e22ebe6cb8844a0a6931d0e3d1734455...     17  0x975a256221f3d3c10e22c76b143e4333908ea1c3  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a                 0           124210            23000000000  0xcf6ff173000000000000000000000000000000000000...                       124210            124210                      NaN          NaN             1.0  0x76d0184cf511788032a74a1fb91146e63f43dd53          UVC  UniversalCoin             5.0   4000000000000000  0x76d0184cf511788032a74a1fb91146e63f43dd53  0x6080604052600436106100fc576000357c0100000000...  ['0x06fdde03', '0x095ea7b3', '0x18160ddd', '0x...      True      False  2019-10-27 09:51:47+00:00  2019-10-27         9067987  0x993075de383faf5ce67fa7067980789f0c2c25516aa5...
3  0xcdb66b2f5bb2e22ebe6cb8844a0a6931d0e3d1734455...                0.0  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x76d0184cf511788032a74a1fb91146e63f43dd53           0  0xa9059cbb000000000000000000000000b955de52193c...  0x00000000000000000000000000000000000000000000...    64732.0         17580.0          0  2019-11-16 03:58:49+00:00         9197987  0x69ef40193e817e181aab1f5d29ecc118ee994d3fa2d0...  0x76d0184cf511788032a74a1fb91146e63f43dd53  0x975a256221f3d3c10e22c76b143e4333908ea1c3  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a         100000000000          0  0xcdb66b2f5bb2e22ebe6cb8844a0a6931d0e3d1734455...     17  0x975a256221f3d3c10e22c76b143e4333908ea1c3  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a                 0           124210            23000000000  0xcf6ff173000000000000000000000000000000000000...                       124210            124210                      NaN          NaN             1.0  0x76d0184cf511788032a74a1fb91146e63f43dd53          UVC  UniversalCoin             5.0   4000000000000000  0x76d0184cf511788032a74a1fb91146e63f43dd53  0x6080604052600436106100fc576000357c0100000000...  ['0x06fdde03', '0x095ea7b3', '0x18160ddd', '0x...      True      False  2019-10-27 09:51:47+00:00  2019-10-27         9067987  0x993075de383faf5ce67fa7067980789f0c2c25516aa5...
4  0xb81ea8f43d6a854857e4b5629b8cd4a220f8600c7281...               35.0  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x76d0184cf511788032a74a1fb91146e63f43dd53           0  0xa9059cbb0000000000000000000000008a4c85f14c85...  0x00000000000000000000000000000000000000000000...    67168.0         32580.0          0  2019-11-16 00:32:44+00:00         9197085  0x6c10dfa16665716ab4862ebed78d3abf8a4349d7a848...  0x76d0184cf511788032a74a1fb91146e63f43dd53  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  0x8a4c85f14c855a0a67662ea573038145a4d6c11f                    1         13  0xb81ea8f43d6a854857e4b5629b8cd4a220f8600c7281...    273  0x8a4c85f14c855a0a67662ea573038145a4d6c11f  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a                 0           100000             2000000000  0x514fcac7000000000000000000000000000000000000...                       980420             48301                      NaN          NaN             1.0  0x76d0184cf511788032a74a1fb91146e63f43dd53          UVC  UniversalCoin             5.0   4000000000000000  0x76d0184cf511788032a74a1fb91146e63f43dd53  0x6080604052600436106100fc576000357c0100000000...  ['0x06fdde03', '0x095ea7b3', '0x18160ddd', '0x...      True      False  2019-10-27 09:51:47+00:00  2019-10-27         9067987  0x993075de383faf5ce67fa7067980789f0c2c25516aa5...

In [258]:
contract_to.address.nunique()

112

In [316]:
# Concat ENS and ENS history

dfENSConcat = pd.concat([contract_from,contract_to],axis=0)
dfENSConcat.head(10)

                                    transaction_hash  transaction_index                          trace_from_address                            trace_to_address        trace_value                                        trace_input                                       trace_output  trace_gas  trace_gas_used  subtraces          block_timestamp_x  block_number_x                                       block_hash_x                      token_transfer_address                 token_transfer_from_address                   token_transfer_to_address token_transfer_value  log_index                                               hash  nonce                    transaction_from_address                      transaction_to_address    transaction_value  transaction_gas  transaction_gas_price transaction_input  receipt_cumulative_gas_used  receipt_gas_used receipt_contract_address receipt_root  receipt_status                               token_address token_symbol token_name  token_decimals token_total_supply                                     address                                           bytecode                                 function_sighashes  is_erc20  is_erc721          block_timestamp_y  block_Date  block_number_y                                       block_hash_y
0  0x3c2a709cee3a943c4c16fbeeaf3e84c38f7c937a47e2...                7.0  0x09aced531359ceffad9759a9252e1d82e3557eb2  0xf5269caa54f1f776dd996db35992d599e14d8a3b                  0  0xfde9cded000000000000000000000000000000000000...  0x00000000000000000000000000000000000000000000...   301428.0          3279.0          0  2019-11-16 01:09:22+00:00         9197228  0x6f6ac9e905b3f0c8f38d64e569efbe30838f90bad3b4...  0xa4d3a7b00056cc5d8206b3b2983bfe0c107d90da  0x0000000000000000000000000000000000000000  0x899fcb4950410ece13a916781c9a339c191ba1b9   468063950110049213          4  0x3c2a709cee3a943c4c16fbeeaf3e84c38f7c937a47e2...     85  0x899fcb4950410ece13a916781c9a339c191ba1b9  0xf5269caa54f1f776dd996db35992d599e14d8a3b  1000000000000000000           350000             2000000000                0x                       341603            194603                      NaN          NaN             1.0  0xa4d3a7b00056cc5d8206b3b2983bfe0c107d90da          MET  Metronome            18.0                  0  0x09aced531359ceffad9759a9252e1d82e3557eb2  0x6080604052600436106100985763ffffffff7c010000...  ['0x2af4c31e', '0x378252f2', '0x50b48c5e', '0x...     False      False  2019-06-24 21:25:13+00:00  2019-06-24         8285384  0x315a86187579161f09a564049868d881347105425321...
1  0x3c2a709cee3a943c4c16fbeeaf3e84c38f7c937a47e2...                7.0  0x09aced531359ceffad9759a9252e1d82e3557eb2  0xf5269caa54f1f776dd996db35992d599e14d8a3b                  0                                         0x496a698d  0x00000000000000000000000000000000000000000000...   307201.0          3324.0          0  2019-11-16 01:09:22+00:00         9197228  0x6f6ac9e905b3f0c8f38d64e569efbe30838f90bad3b4...  0xa4d3a7b00056cc5d8206b3b2983bfe0c107d90da  0x0000000000000000000000000000000000000000  0x899fcb4950410ece13a916781c9a339c191ba1b9   468063950110049213          4  0x3c2a709cee3a943c4c16fbeeaf3e84c38f7c937a47e2...     85  0x899fcb4950410ece13a916781c9a339c191ba1b9  0xf5269caa54f1f776dd996db35992d599e14d8a3b  1000000000000000000           350000             2000000000                0x                       341603            194603                      NaN          NaN             1.0  0xa4d3a7b00056cc5d8206b3b2983bfe0c107d90da          MET  Metronome            18.0                  0  0x09aced531359ceffad9759a9252e1d82e3557eb2  0x6080604052600436106100985763ffffffff7c010000...  ['0x2af4c31e', '0x378252f2', '0x50b48c5e', '0x...     False      False  2019-06-24 21:25:13+00:00  2019-06-24         8285384  0x315a86187579161f09a564049868d881347105425321...
2  0x3c2a709cee3a943c4c16fbeeaf3e84c38f7c937a47e2...                7.0  0x09aced531359ceffad9759a9252e1d82e3557eb2  0xf5269caa54f1f776dd996db35992d599e14d8a3b                  0                                         0x21288400  0x00000000000000000000000000000000000000000000...   309694.0           689.0          0  2019-11-16 01:09:22+00:00         9197228  0x6f6ac9e905b3f0c8f38d64e569efbe30838f90bad3b4...  0xa4d3a7b00056cc5d8206b3b2983bfe0c107d90da  0x0000000000000000000000000000000000000000  0x899fcb4950410ece13a916781c9a339c191ba1b9   468063950110049213          4  0x3c2a709cee3a943c4c16fbeeaf3e84c38f7c937a47e2...     85  0x899fcb4950410ece13a916781c9a339c191ba1b9  0xf5269caa54f1f776dd996db35992d599e14d8a3b  1000000000000000000           350000             2000000000                0x                       341603            194603                      NaN          NaN             1.0  0xa4d3a7b00056cc5d8206b3b2983bfe0c107d90da          MET  Metronome            18.0                  0  0x09aced531359ceffad9759a9252e1d82e3557eb2  0x6080604052600436106100985763ffffffff7c010000...  ['0x2af4c31e', '0x378252f2', '0x50b48c5e', '0x...     False      False  2019-06-24 21:25:13+00:00  2019-06-24         8285384  0x315a86187579161f09a564049868d881347105425321...
3  0x3c2a709cee3a943c4c16fbeeaf3e84c38f7c937a47e2...                7.0  0x09aced531359ceffad9759a9252e1d82e3557eb2  0x567eebb6397cc8345e5a7eae288994bf45fdf85b  65497181753650651                                         0x7679a816                                                 0x   284651.0          4874.0          1  2019-11-16 01:09:22+00:00         9197228  0x6f6ac9e905b3f0c8f38d64e569efbe30838f90bad3b4...  0xa4d3a7b00056cc5d8206b3b2983bfe0c107d90da  0x0000000000000000000000000000000000000000  0x899fcb4950410ece13a916781c9a339c191ba1b9   468063950110049213          4  0x3c2a709cee3a943c4c16fbeeaf3e84c38f7c937a47e2...     85  0x899fcb4950410ece13a916781c9a339c191ba1b9  0xf5269caa54f1f776dd996db35992d599e14d8a3b  1000000000000000000           350000             2000000000                0x                       341603            194603                      NaN          NaN             1.0  0xa4d3a7b00056cc5d8206b3b2983bfe0c107d90da          MET  Metronome            18.0                  0  0x09aced531359ceffad9759a9252e1d82e3557eb2  0x6080604052600436106100985763ffffffff7c010000...  ['0x2af4c31e', '0x378252f2', '0x50b48c5e', '0x...     False      False  2019-06-24 21:25:13+00:00  2019-06-24         8285384  0x315a86187579161f09a564049868d881347105425321...
4  0xfcb065dda0ac9a55bda686b6ba17a4589510198160de...                4.0  0x09aced531359ceffad9759a9252e1d82e3557eb2  0xf5269caa54f1f776dd996db35992d599e14d8a3b                  0                                         0x496a698d  0x00000000000000000000000000000000000000000000...   307201.0          3324.0          0  2019-11-12 00:04:18+00:00         9170672  0xc29f78fc6b752ff54df4206d772dc87747ac0f16e198...  0xa4d3a7b00056cc5d8206b3b2983bfe0c107d90da  0x0000000000000000000000000000000000000000  0x899fcb4950410ece13a916781c9a339c191ba1b9   468063950110049213          4  0xfcb065dda0ac9a55bda686b6ba17a4589510198160de...     75  0x899fcb4950410ece13a916781c9a339c191ba1b9  0xf5269caa54f1f776dd996db35992d599e14d8a3b   500000000000000000           350000             2000000000                0x                       273929            189929                      NaN          NaN             1.0  0xa4d3a7b00056cc5d8206b3b2983bfe0c107d90da          MET  Metronome            18.0                  0  0x09aced531359ceffad9759a9252e1d82e3557eb2  0x6080604052600436106100985763ffffffff7c010000...  ['0x2af4c31e', '0x378252f2', '0x50b48c5e', '0x...     False      False  2019-06-24 21:25:13+00:00  2019-06-24         8285384  0x315a86187579161f09a564049868d881347105425321...
5  0xfcb065dda0ac9a55bda686b6ba17a4589510198160de...                4.0  0x09aced531359ceffad9759a9252e1d82e3557eb2  0xf5269caa54f1f776dd996db35992d599e14d8a3b                  0                                         0x21288400  0x00000000000000000000000000000000000000000000...   309694.0           689.0          0  2019-11-12 00:04:18+00:00         9170672  0xc29f78fc6b752ff54df4206d772dc87747ac0f16e198...  0xa4d3a7b00056cc5d8206b3b2983bfe0c107d90da  0x0000000000000000000000000000000000000000  0x899fcb4950410ece13a916781c9a339c191ba1b9   468063950110049213          4  0xfcb065dda0ac9a55bda686b6ba17a4589510198160de...     75  0x899fcb4950410ece13a916781c9a339c191ba1b9  0xf5269caa54f1f776dd996db35992d599e14d8a3b   500000000000000000           350000             2000000000                0x                       273929            189929                      NaN          NaN             1.0  0xa4d3a7b00056cc5d8206b3b2983bfe0c107d90da          MET  Metronome            18.0                  0  0x09aced531359ceffad9759a9252e1d82e3557eb2  0x6080604052600436106100985763ffffffff7c010000...  ['0x2af4c31e', '0x378252f2', '0x50b48c5e', '0x...     False      False  2019-06-24 21:25:13+00:00  2019-06-24         8285384  0x315a86187579161f09a564049868d881347105425321...
6  0xfcb065dda0ac9a55bda686b6ba17a4589510198160de...                4.0  0x09aced531359ceffad9759a9252e1d82e3557eb2  0x567eebb6397cc8345e5a7eae288994bf45fdf85b  65426023606211705                                         0x7679a816                                                 0x   284651.0          4874.0          1  2019-11-12 00:04:18+00:00         9170672  0xc29f78fc6b752ff54df4206d772dc87747ac0f16e198...  0xa4d3a7b00056cc5d8206b3b2983bfe0c107d90da  0x0000000000000000000000000000000000000000  0x899fcb4950410ece13a916781c9a339c191ba1b9   468063950110049213          4  0xfcb065dda0ac9a55bda686b6ba17a4589510198160de...     75  0x899fcb4950410ece13a916781c9a339c191ba1b9  0xf5269caa54f1f776dd996db35992d599e14d8a3b   500000000000000000           350000             2000000000                0x                       273929            189929                      NaN          NaN             1.0  0xa4d3a7b00056cc5d8206b3b2983bfe0c107d90da          MET  Metronome            18.0                  0  0x09aced531359ceffad9759a9252e1d82e3557eb2  0x6080604052600436106100985763ffffffff7c010000...  ['0x2af4c31e', '0x378252f2', '0x50b48c5e', '0x...     False      False  2019-06-24 21:25:13+00:00  2019-06-24         8285384  0x315a86187579161f09a564049868d881347105425321...
7  0xfcb065dda0ac9a55bda686b6ba17a4589510198160de...                4.0  0x09aced531359ceffad9759a9252e1d82e3557eb2  0xf5269caa54f1f776dd996db35992d599e14d8a3b                  0  0xfde9cded000000000000000000000000000000000000...  0x00000000000000000000000000000000000000000000...   301428.0          3279.0          0  2019-11-12 00:04:18+00:00         9170672  0xc29f78fc6b752ff54df4206d772dc87747ac0f16e198...  0xa4d3a7b00056cc5d8206b3b2983bfe0c107d90da  0x0000000000000000000000000000000000000000  0x899fcb4950410ece13a916781c9a339c191ba1b9   468063950110049213          4  0xfcb065dda0ac9a55bda686b6ba17a4589510198160de...     75  0x899fcb4950410ece13a916781c9a339c191ba1b9  0xf5269caa54f1f776dd996db35992d599e14d8a3b   500000000000000000           350000             2000000000                0x                       273929            189929                      NaN          NaN             1.0  0xa4d3a7b00056cc5d8206b3b2983bfe0c107d90da          MET  Metronome            18.0                  0  0x09aced531359ceffad9759a9252e1d82e3557eb2  0x6080604052600436106100985763ffffffff7c010000...  ['0x2af4c31e', '0x378252f2', '0x50b48c5e', '0x...     False      False  2019-06-24 21:25:13+00:00  2019-06-24         8285384  0x315a86187579161f09a564049868d881347105425321...
8  0xcab257301bb291e7fae69a49e3a2616f32c3d275130a...                4.0  0x09aced531359ceffad9759a9252e1d82e3557eb2  0xf5269caa54f1f776dd996db35992d599e14d8a3b                  0                                         0x496a698d  0x00000000000000000000000000000000000000000000...   307201.0          3324.0          0  2019-11-20 01:09:46+00:00         9223520  0x88050f01b14785905742b0fe50fc5e622c930955bb05...  0xa4d3a7b00056cc5d8206b3b2983bfe0c107d90da  0x0000000000000000000000000000000000000000  0x899fcb4950410ece13a916781c9a339c191ba1b9   468063950110049213          8  0xcab257301bb291e7fae69a49e3a2616f32c3d275130a...     96  0x899fcb4950410ece13a916781c9a339c191ba1b9  0xf5269caa54f1f776dd996db35992d599e14d8a3b  1000000000000000000           350000             2000000000                0x                       316267            194603                      NaN          NaN             1.0  0xa4d3a7b00056cc5d8206b3b2983bfe0c107d90da          MET  Metronome            18.0                  0  0x09aced531359ceffad9759a9252e1d82e3557eb2  0x6080604052600436106100985763ffffffff7c010000...  ['0x2af4c31e', '0x378252f2', '0x50b48c5e', '0x...     False      False  2019-06-24 21:25:13+00:00  2019-06-24         8285384  0x315a86187579161f09a564049868d881347105425321...
9  0xcab257301bb291e7fae69a49e3a2616f32c3d275130a...                4.0  0x09aced531359ceffad9759a9252e1d82e3557eb2  0x567eebb6397cc8345e5a7eae288994bf45fdf85b  65601693860489887                                         0x7679a816                                                 0x   284651.0          4874.0          1  2019-11-20 01:09:46+00:00         9223520  0x88050f01b14785905742b0fe50fc5e622c930955bb05...  0xa4d3a7b00056cc5d8206b3b2983bfe0c107d90da  0x0000000000000000000000000000000000000000  0x899fcb4950410ece13a916781c9a339c191ba1b9   468063950110049213          8  0xcab257301bb291e7fae69a49e3a2616f32c3d275130a...     96  0x899fcb4950410ece13a916781c9a339c191ba1b9  0xf5269caa54f1f776dd996db35992d599e14d8a3b  1000000000000000000           350000             2000000000                0x                       316267            194603                      NaN          NaN             1.0  0xa4d3a7b00056cc5d8206b3b2983bfe0c107d90da          MET  Metronome            18.0                  0  0x09aced531359ceffad9759a9252e1d82e3557eb2  0x6080604052600436106100985763ffffffff7c010000...  ['0x2af4c31e', '0x378252f2', '0x50b48c5e', '0x...     False      False  2019-06-24 21:25:13+00:00  2019-06-24         8285384  0x315a86187579161f09a564049868d881347105425321...

In [317]:
headers=PrettyTable(["S.No","Column Name","Record Count","Unique Count","Null Count","Total Count"])
i=1
for col in dfENSConcat.columns:
    headers.add_row([i,col,dfENSConcat[col].count(),dfENSConcat[col].nunique(),
                    dfENSConcat[col].isnull().sum(),dfENSConcat[col].count()+dfENSConcat[col].isnull().sum()])
    i+=1
    
print(headers)

+------+-----------------------------+--------------+--------------+------------+-------------+
| S.No |         Column Name         | Record Count | Unique Count | Null Count | Total Count |
+------+-----------------------------+--------------+--------------+------------+-------------+
|  1   |       transaction_hash      |    963582    |    57682     |     0      |    963582   |
|  2   |      transaction_index      |    963582    |     155      |     0      |    963582   |
|  3   |      trace_from_address     |    963582    |     1010     |     0      |    963582   |
|  4   |       trace_to_address      |    963582    |     260      |     0      |    963582   |
|  5   |         trace_value         |    963582    |     986      |     0      |    963582   |
|  6   |         trace_input         |    963582    |    54328     |     0      |    963582   |
|  7   |         trace_output        |    963582    |     4064     |     0      |    963582   |
|  8   |          trace_gas          |    963582    |    60809     |     0      |    963582   |
|  9   |        trace_gas_used       |    963582    |     5653     |     0      |    963582   |
|  10  |          subtraces          |    963582    |      30      |     0      |    963582   |
|  11  |      block_timestamp_x      |    963582    |    24782     |     0      |    963582   |
|  12  |        block_number_x       |    963582    |    24782     |     0      |    963582   |
|  13  |         block_hash_x        |    963582    |    24782     |     0      |    963582   |
|  14  |    token_transfer_address   |    963582    |      32      |     0      |    963582   |
|  15  | token_transfer_from_address |    963582    |     1382     |     0      |    963582   |
|  16  |  token_transfer_to_address  |    963582    |    24771     |     0      |    963582   |
|  17  |     token_transfer_value    |    963582    |     7863     |     0      |    963582   |
|  18  |          log_index          |    963582    |     241      |     0      |    963582   |
|  19  |             hash            |    963582    |    57682     |     0      |    963582   |
|  20  |            nonce            |    963582    |    23632     |     0      |    963582   |
|  21  |   transaction_from_address  |    963582    |     1779     |     0      |    963582   |
|  22  |    transaction_to_address   |    963581    |      75      |     1      |    963582   |
|  23  |      transaction_value      |    963582    |     281      |     0      |    963582   |
|  24  |       transaction_gas       |    963582    |     1272     |     0      |    963582   |
|  25  |    transaction_gas_price    |    963582    |     130      |     0      |    963582   |
|  26  |      transaction_input      |    963582    |    32706     |     0      |    963582   |
|  27  | receipt_cumulative_gas_used |    963582    |    39407     |     0      |    963582   |
|  28  |       receipt_gas_used      |    963582    |     6477     |     0      |    963582   |
|  29  |   receipt_contract_address  |      1       |      1       |   963581   |    963582   |
|  30  |         receipt_root        |    334689    |    32069     |   628893   |    963582   |
|  31  |        receipt_status       |    628893    |      1       |   334689   |    963582   |
|  32  |        token_address        |    963582    |      32      |     0      |    963582   |
|  33  |         token_symbol        |    963578    |      30      |     4      |    963582   |
|  34  |          token_name         |    963578    |      27      |     4      |    963582   |
|  35  |        token_decimals       |    963539    |      8       |     43     |    963582   |
|  36  |      token_total_supply     |    963582    |      25      |     0      |    963582   |
|  37  |           address           |    963582    |     112      |     0      |    963582   |
|  38  |           bytecode          |    963582    |      96      |     0      |    963582   |
|  39  |      function_sighashes     |    963582    |      54      |     0      |    963582   |
|  40  |           is_erc20          |    963582    |      2       |     0      |    963582   |
|  41  |          is_erc721          |    963582    |      2       |     0      |    963582   |
|  42  |      block_timestamp_y      |    963582    |     111      |     0      |    963582   |
|  43  |          block_Date         |    963582    |      37      |     0      |    963582   |
|  44  |        block_number_y       |    963582    |     111      |     0      |    963582   |
|  45  |         block_hash_y        |    963582    |     111      |     0      |    963582   |
+------+-----------------------------+--------------+--------------+------------+-------------+

In [318]:
dfENSConcat.drop(['block_timestamp_y',
            'block_number_y',
            'block_hash_y'
           ], axis=1, inplace=True)

In [319]:
dfENSConcat.columns = ['transaction_hash',
                       'transaction_index',
                       'trace_from_address',
                       'trace_to_address',
                       'trace_value',
                       'trace_input',
                       'trace_output',
                       'trace_gas',
                       'trace_gas_used',
                       'subtraces',
                       'block_timestamp',
                       'block_number',
                       'block_hash',
                       'token_transfer_address',
                       'token_transfer_from_address',
                       'token_transfer_to_address',
                       'token_transfer_value',
                       'log_index',
                       'hash',
                       'nonce',
                       'transaction_from_address',
                       'transaction_to_address',
                       'transaction_value',
                       'transaction_gas',
                       'transaction_gas_price',
                       'transaction_input',
                       'receipt_cumulative_gas_used',
                       'receipt_gas_used',
                       'receipt_contract_address',
                       'receipt_root',
                       'receipt_status',
                       'token_address',
                       'token_symbol',
                       'token_name',
                       'token_decimals',
                       'token_total_supply',
                       'Contract_address',
                       'Contract_bytecode',
                       'Contract_function_sighashes',
                       'Contract_is_erc20',
                       'Contract_is_erc721',
                       'Contract_block_Date'
                  ]

In [321]:
# removing null records
dfENSConcat = dfENSConcat[~dfENSConcat.token_symbol.isnull() & 
                          ~dfENSConcat.token_name.isnull() & 
                          ~dfENSConcat.token_decimals.isnull() &
                          ~dfENSConcat.transaction_to_address.isnull()
                         ]

In [322]:
dfENSConcat["receipt_status"].fillna(0, inplace=True)

In [323]:
dfENSConcat.drop(['receipt_contract_address',
            'receipt_root'
           ], axis=1, inplace=True)

In [326]:
dfENSConcat.reset_index(inplace=True, drop=True)

In [327]:
headers=PrettyTable(["S.No","Column Name","Record Count","Unique Count","Null Count","Total Count"])
i=1
for col in dfENSConcat.columns:
    headers.add_row([i,
                     col,
                     dfENSConcat[col].count(),
                     dfENSConcat[col].nunique(),
                     dfENSConcat[col].isnull().sum(),
                     dfENSConcat[col].count()+dfENSConcat[col].isnull().sum()])
    i+=1
    
print(headers)

+------+-----------------------------+--------------+--------------+------------+-------------+
| S.No |         Column Name         | Record Count | Unique Count | Null Count | Total Count |
+------+-----------------------------+--------------+--------------+------------+-------------+
|  1   |       transaction_hash      |    963534    |    57636     |     0      |    963534   |
|  2   |      transaction_index      |    963534    |     155      |     0      |    963534   |
|  3   |      trace_from_address     |    963534    |     1008     |     0      |    963534   |
|  4   |       trace_to_address      |    963534    |     257      |     0      |    963534   |
|  5   |         trace_value         |    963534    |     984      |     0      |    963534   |
|  6   |         trace_input         |    963534    |    54296     |     0      |    963534   |
|  7   |         trace_output        |    963534    |     4064     |     0      |    963534   |
|  8   |          trace_gas          |    963534    |    60804     |     0      |    963534   |
|  9   |        trace_gas_used       |    963534    |     5648     |     0      |    963534   |
|  10  |          subtraces          |    963534    |      30      |     0      |    963534   |
|  11  |       block_timestamp       |    963534    |    24736     |     0      |    963534   |
|  12  |         block_number        |    963534    |    24736     |     0      |    963534   |
|  13  |          block_hash         |    963534    |    24736     |     0      |    963534   |
|  14  |    token_transfer_address   |    963534    |      30      |     0      |    963534   |
|  15  | token_transfer_from_address |    963534    |     1382     |     0      |    963534   |
|  16  |  token_transfer_to_address  |    963534    |    24745     |     0      |    963534   |
|  17  |     token_transfer_value    |    963534    |     7823     |     0      |    963534   |
|  18  |          log_index          |    963534    |     241      |     0      |    963534   |
|  19  |             hash            |    963534    |    57636     |     0      |    963534   |
|  20  |            nonce            |    963534    |    23632     |     0      |    963534   |
|  21  |   transaction_from_address  |    963534    |     1778     |     0      |    963534   |
|  22  |    transaction_to_address   |    963534    |      73      |     0      |    963534   |
|  23  |      transaction_value      |    963534    |     279      |     0      |    963534   |
|  24  |       transaction_gas       |    963534    |     1267     |     0      |    963534   |
|  25  |    transaction_gas_price    |    963534    |     129      |     0      |    963534   |
|  26  |      transaction_input      |    963534    |    32673     |     0      |    963534   |
|  27  | receipt_cumulative_gas_used |    963534    |    39392     |     0      |    963534   |
|  28  |       receipt_gas_used      |    963534    |     6471     |     0      |    963534   |
|  29  |        receipt_status       |    963534    |      2       |     0      |    963534   |
|  30  |        token_address        |    963534    |      30      |     0      |    963534   |
|  31  |         token_symbol        |    963534    |      29      |     0      |    963534   |
|  32  |          token_name         |    963534    |      26      |     0      |    963534   |
|  33  |        token_decimals       |    963534    |      7       |     0      |    963534   |
|  34  |      token_total_supply     |    963534    |      23      |     0      |    963534   |
|  35  |       Contract_address      |    963534    |     110      |     0      |    963534   |
|  36  |      Contract_bytecode      |    963534    |      94      |     0      |    963534   |
|  37  | Contract_function_sighashes |    963534    |      53      |     0      |    963534   |
|  38  |      Contract_is_erc20      |    963534    |      2       |     0      |    963534   |
|  39  |      Contract_is_erc721     |    963534    |      1       |     0      |    963534   |
|  40  |     Contract_block_Date     |    963534    |      37      |     0      |    963534   |
+------+-----------------------------+--------------+--------------+------------+-------------+

In [328]:
# make sure that number of duplicate rows are zero 
# True indicates no duplicate record
sum(dfENSConcat.duplicated(subset=None, keep='first')) == 0

True

In [329]:
dfENSConcat.to_csv('/Users/rparama/Downloads/Dataset/ENSConcat.csv',index=False)